<template>
  <div>
    <section class="hero is-info">
<div class="hero-body">
        <div class="container">
          <h1 class="title">Research</h1>
        </div>
      </div>
    </section>
    <section class="section">
      <div class="container">
        <div class="content">
          <p>I have done some research. My research interests are mainly in computer architecture, operating systems, and security. More specifically, I am currently most interested in trusted execution environments (TEEs), sandboxing and isolation, and heterogeneous computing.</p>
          <h2>Publications</h2>
          <div class="card mb-4">
            <div class="card-content p-4">
              <p class="title is-5 mb-1"><a href="https://dl.acm.org/doi/abs/10.1145/3757347.3759137">Adaptive and Efficient Dynamic Memory Management for Hardware Enclaves</a></p>
              <p>Vijay Dhanraj, Harpreet Singh Chawla, Daniel Manila, <strong>Eric Thomas Schneider</strong>, Erica Fu, Mona Vij, Chia-Che Tsai, Donald E. Porter</p>
              <p class="has-text-grey">ACM International Systems and Storage Conference (SYSTOR), 2025</p>
            </div>
          </div>
          <div class="card mb-4">
            <div class="card-content p-4">
              <p class="title is-5 mb-1"><a href="/Mechanisms of Memory Protection.pdf">Mechanisms of Memory Protection</a></p>
              <p><strong>Eric Thomas Schneider</strong></p>
              <p class="has-text-grey">MS Project</p>
            </div>
          </div>

          <h2>Service</h2>
          <ul>
            <li><a href="https://sites.google.com/view/asplos26aec/home">ASPLOS AEC PC 2026</a></li>
            <li><a href="https://sites.google.com/view/asplos25aec/home">ASPLOS AEC PC 2025</a></li>
            <li><a href="https://sites.google.com/view/asplos24aec/home">ASPLOS AEC PC 2024</a></li>
          </ul>

          <h2>Research Projects</h2>
          <ul>
            <li>Adapting sandboxing to TEEs; this project is my current focus. Inspired by papers like <a href="https://dl.acm.org/doi/pdf/10.1145/3231594">Ryoan</a>, I am exploring a powerful threat model where neither an application nor a hypervisor is not trusted to not leak sensitive data. We are exploring covert channels between an application and hypervisor and defenses for them, particularly for large language models. I am working on a paper on this topic.</li>
            <li>"SATerm" - eBPF Termination. Under <a href="https://people.cs.vt.edu/djwillia/">Professor Dan Williams</a> (<a href="https://rosalab.github.io/">ROSA</a>), I contributed to a project exploring the termination of long-running eBPF extensions. We submitted to USENIX ATC '25 with mixed reviews; currently the paper is being lead by another student, and some of the work is being upstreamed to Linux.</li>
            <li>Media Attestation. This project is being lead by <a href="https://jessewei.dev/">Jesse Wei</a>. Under <a href="https://andrewkwong.org/">Professor Andrew Kwong</a>, we are exploring using ARM CCA and the <a href="https://c2pa.org/">C2PA standard</a> to prove the authenticity of images generated by a mobile camera.</li>
            <li>"Native Enclave" - for our <a href="https://andrewkwong.org/comp790-185.html">Research in Security</a> class project, I worked with Yulu Pan on porting <a href="https://github.com/keystone-enclave/keystone">Keystone</a>, a RISC-V TEE implementation, to uClinux (Linux without virtual memory), to try to explore how the idea of TEEs could be extended to become a first-class memory protection mechanism in a "native enclave" system. Unfortunately, Keystone is pretty tied to virtual memory, but I hope to revisit this idea for a future project.</li>
            <li><a href="https://github.com/ac-freeman/adder-codec-rs">ADΔER</a>. Under <a href="https://acfreeman.dev/">Andrew Freeman</a>, Professor Ketan Mayer-Patel, and <a href="https://www.cs.unc.edu/~montek/">Professor Montek Singh</a>, I contributed towards the ADΔER asyncronous video research software suite. In Rust, I contributed a transcoder bandwidth limiting feature, implemented an event logging feature for the Rust implementation of the DVS Fast algorithm, fixed a couple Windows-related ADΔER issues, and updated the CI (with GitHub Actions). I also did a survey paper. In summer 2023, I was funded by the Laboratory for Analytical Sciences (LAS) for this work.</li>
            <li><a href="https://github.com/NIRALUser/NeuroRuler">NeuroRuler</a>. Under <a href="https://www.cs.unc.edu/~styner/">Professor Martin Styner</a> (<a href="https://www.med.unc.edu/psych/research/niral/">NIRAL</a>), with a few other students, I helped create this research software, written in Python. Basically, using MRI data, it will calculate head circumference given a particular "slice" of the brain. The software has some options for rotation, smoothing, threshold, and a batch API via the command line. It is being used by some neuro imaging researchers in Martin's lab.</li>
            <li><a href="https://github.com/gramineproject/gramine">Gramine</a> - Improving SGX Performance with Cooperative, Dynamic Page Management. Under <a href="https://www.cs.unc.edu/~porter/">Professor Donald Porter</a> (<a href="https://oscarlab.github.io/">OSCAR</a>), I contributed to this paper mainly with writing and benchmarking.</li>
          </ul>
        </div>
      </div>
    </section>
  </div>
</template>
<script setup lang="ts">
useSeoMeta({
  title: 'Research',
  description: 'Research by Eric Schneider on trusted execution environments (TEEs), sandboxing, eBPF termination, and heterogeneous computing.',
  ogTitle: 'Research – Eric Schneider',
  ogDescription: 'Research on trusted execution environments (TEEs), sandboxing, eBPF termination, and heterogeneous computing.',
  ogImage: 'https://eric-unc.tech/eric.png',
  twitterCard: 'summary',
})
</script>
