<template>
  <div>
    <section class="hero is-info">
<div class="hero-body">
        <div class="container">
          <h1 class="title">Software</h1>
        </div>
      </div>
    </section>
    <section class="section">
      <div class="container">
      <div class="content">
        <p>Since I started programming in 2014, I'm accumulated a large albeit odd set of projects that I have made or contributed to. Here is my "software portfolio".</p>
        <h2>Industry experience</h2>
        <p>In the summer of 2021, I was an intern for VMware's Uhana team. <a href="https://docs.vmware.com/en/Uhana-by-VMware/1.0/uhana_piran_1_3/GUID-overview.html">Uhana</a> is a real-time big data platform for telecommunications, which generates and analyzes KPIs (key performance indicators) for 4G and 5G radio access networks (RAN). I worked on migrating the decoder service from using Apache Kafka Streams to Apache Flink. The decoder is an early part of the pipeline, which converts a stream of various formats (binary, JSON, ASN) into a unified format (protobufs). I enjoyed working at VMware, and also enjoyed mentoring for VMware High School Hacks, and participating in the intern borathon. I returned in the summer of 2022 to the same team, but with a more difficult project: splitting the overly complicated Flink-based streaker service into two smaller services: a session collator and a KPI composer. The composition of KPIs is the most important part of the Uhana platform, so being able to increase the stability of that component of the pipeline was a pleasure.</p>
        <p>In the summer of 2024, I was an intern for Nutanix's NDB team. <a href="https://www.nutanix.com/products/database-service">NDB/Nutanix Database Service</a> is a Database-as-a-Service platform designed to support on-premise environments. My intern project was to implement an <a href="https://www.nutanix.com/products/objects">Object Store</a> storage consumption monitoring feature into NDB, but more of my work was contributing to NDB support for Object Store and <a href="https://portal.nutanix.com/page/documents/details?targetId=Prism-Central-Guide-vpc_7_3:mul-pc-overview-c.html">Prism Central</a>. The main technologies used were Spring and React. I enjoyed working at Nutanix, and I also enjoyed participating in their intern hackathon.</p>

        <h2>Web</h2>
        <p>My first website, using basic HTML and CSS, is so bad that I don't want to link to it. But this one is okay! I originally wrote this with HTML/CSS plus jQuery, but I migrated to Nuxt.js/Vue.js (specifically Nuxt 3/Vue 3, which uses a bit of TypeScript). Styled with Bulma, hosted using GitHub Pages. Other projects include a <a href="https://devpost.com/software/mad-muzzic">React/Bulma frontend</a> for a hackathon, a <a href="https://comp211-20f.github.io/">course review website</a> (also using Bulma), and a <a href="https://github.com/calendar-gang/tar-heel-calendar">Tar Heel Calendar</a>, using React, Bulma (wow), express.js, MariaDB, and Heroku. For that project, I basically made the entire backend, and the rest of the team worked on the frontend. Besides from those, I have web experience from being a wiki administrator (discussed a few sections down), and from a little bit of frontend work done at Nutanix (discussed a section above).</p>

        <h2>Languages/Systems</h2>
        <p>For a school project, I created a <a href="https://github.com/eric-unc/520-compiler">"mini" Java compiler</a> targeting a custom VM. My compiler supports basic integer and boolean operations, arrays, basic control logic, and some level of OOP. There's also support for field initialization, constructors, for loops, and some level of broken support for overloading. This class would inspire me to make a toy programming language called <a href="https://github.com/eric-unc/limp">Limp</a> in Rust for a hackathon; I would use this as a prototype for <a href="https://github.com/eric-unc/psil">Psil</a>, a more powerful Lisp-like language, written in Rust. It has a standard variety of types (numbers, booleans, strings, symbols, procedures), some composite types (lists, tables), bindings, control logic, a mix of functional/procedural programming, a native documentation generator (like Javadocs), and a decently sized standard library (currently with over 50 built-in procedures).</p>
        <p>For another school project called "JOS", I implement key portions of an operating system (using C and Assembly). The OS supports boot loading, virtual memory, processes/environments, multiprogramming, a file system and shell, and a partial implementation of a hypervisor. It also has special support for floating point operations.</p>

        <h2>Hardware</h2>
        <p>Whoops, this isn't software! Alas; <a href="https://jessewei.dev/projects/leds/">"touching wires and breadboards is good for the CS major"</a>. Over a winter break, I was working on <a href="https://eater.net/8bit">an 8-bit breadboard computer</a>, which is 80% done. Unfortunately I never finished it. <a href="/computer.jpg">Here</a> is a picture of it.</p>
        <p>For a class, I implemented a simple single-cycle MIPS processor in Verilog for an FPGA, and then wrote a "shell" demo for it in Assembly. It supports 12 simple commands, ~120 characters (including several special characters), supported by ~900 instructions and ~900 words in static memory. I drew each character myself, and it shows. You can see my demo <a href="https://www.youtube.com/watch?v=AlkD0imRwz8">here</a>.</p>

        <h2>Minecraft mods</h2>
        <p>I originally gained an appreciation for computer programming through <a href="https://ftb.fandom.com/wiki/Mods">Minecraft modding</a>. Although I am no longer very active in the scene, I have created, taken over, or contributed towards several well-used Minecraft mods. <a href="https://www.curseforge.com/minecraft/mc-mods/nuclear-control-2">Nuclear Control 2</a> (now discontinued) is probably my biggest project, which has more than 6.3 million downloads. Notable other projects include the <a href="https://www.curseforge.com/minecraft/mc-mods/afsu-mod">AFSU Mod</a> (with 215k downloads), <a href="https://www.curseforge.com/minecraft/mc-mods/flaxbeards-steam-power">Flaxbeard's Steam Power</a> (also known as Esteemed Innovation, with 1m downloads), <a href="https://www.curseforge.com/minecraft/mc-mods/world-control">World Control</a> (1.3m downloads), <a href="https://www.curseforge.com/minecraft/mc-mods/long-fall-boots">Long Fall Boots</a> (18.5m downloads), <a href="https://www.curseforge.com/minecraft/mc-mods/bonemealable-babies">Bonemealable Babies</a> (11k downloads), and <a href="https://www.curseforge.com/minecraft/mc-mods/huesodewiki">HuesoDeWiki</a> (with 7k downloads). There are also a few early projects (<a href="https://github.com/xbony2/Bitm">Bitm</a>, <a href="https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2076392-modjam4-1-7-bonys-desertcraft">Bony's Desertcraft</a>, <a href="https://github.com/xbony2/IndustrialEx">IndustrialEx</a> <a href="https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2323075-1-7-10-shinystones-mod-2">ShinyStones Mod 2</a>, <a href="https://github.com/xbony2/AntiEndPortalMod">AntiEndPortalMod</a>). All are written in Java.</p>

        <h2>Wiki administration</h2>
        <p>Creating mods accidentally brought me deep into the world of documenting mods. Although nowadays I am not very active, I am an administrator of and a major contributor (with over 55,000 edits) towards the <a href="https://ftb.fandom.com/wiki/FTB_Wiki">Official FTB Wiki</a>, the largest, most popular and most up-to-date centralized repository of knowledge on modded Minecraft. In August 2016, I was awarded <a href="https://help.fandom.com/wiki/Editor_of_the_Month">Gamepedia Editor of the Month</a> for my "hard work across Gamepedia." Much of my contributions are not writing, but are of a technical nature, including some on-wiki scripting (in JavaScript, Lua, and "wikitext"), bot-making (<a href="https://github.com/xbony2/Experimental-Self-Aware-Electronic-Based-Space-Analyzing-Droid">"ESAEBSAD"</a> in Ruby for IRC, <a href="https://github.com/xbony2/ESAEBSAD2">ESAEBSAD2</a> in Groovy for Discord, <a href="https://github.com/xbony2/ESAEBSAD3">ESAEBSAD3</a> in Ruby...), <a href="https://github.com/FTB-Gamepedia/ATT-9001">a tool for automatically importing translations</a>, <a href="https://www.curseforge.com/minecraft/mc-mods/huesodewiki">a mod to help editors</a>, and a lot of random run-once scripts and technical contributions to other wiki-related projects. When I was involved in writing, much of the writing involved carefully analyzing Java (rarely Scala/Kotlin) code. Non-technical contributions include refining wiki guidelines and guides, managing the translation projects, and organizing events (editathons and representation at virtual modded events).</p>
        <p>Besides from the FTB Wiki, I was briefly the sole admin for a <a href="https://tmole.fandom.com/wiki/The_Madness_of_Little_Emma_Wiki">smaller game wiki</a> (doing ~1.5k edits), and I was part of the <a href="https://help.fandom.com/wiki/Gamepedia_Rapid_Anti-Spam_Patrol">Gamepedia Rapid Anti-Spam Patrol</a>, an initiative to revert vandalism (rarely spam) across the Gamepedia wiki farm. Also, when I'm browsing wikis, I like to fix anything broken I see, so you might see my name elsewhere in the wiki world.</p>

        <h2>Potpourri</h2>
        <p>Here's a bunch of other random stuff I worked on that I think is cool: <a href="https://github.com/a8675309/HackNCSilentDisco0">an Android app for practicing Spanish or French</a> (made for my first hackathon), a <a href="https://github.com/eric-unc/401hackathon">game written with Java Swing</a> (for a class hackathon), <a href="https://github.com/eric-unc/a8-conway-the-gamer">Conway's Game of Life</a> (also using Java Swing), a <a href="https://globalgamejam.org/2020/games/breath-8">Unity/C# game</a> (for another hackathon), a <a href="https://github.com/eric-unc/MATH-383L-final">MATLAB project for a class</a>, a <a href="https://devpost.com/software/betterthanvim">primitive CLI editor written in Rust</a> (for a hackathon, later <a href="https://github.com/eric-unc/WorseThanVim">ported to C++</a>), a <a href="https://github.com/eric-unc/hacknc2021">calculator written in Rust</a> (for another hackathon, which you can still access <a href="https://eric-unc.tech/hacknc2021/">through Wasm</a>), and a <a href="https://github.com/eric-unc/magnum">small virtual machine written in Rust</a> (for a hackathon, which I actually was given first place for).</p>
      </div>
      </div>
    </section>
  </div>
</template>
<script setup lang="ts">
useSeoMeta({
  title: 'Software',
  description: 'Software portfolio of Eric Schneider – compilers, operating systems, Minecraft mods, web projects, and more.',
  ogTitle: 'Software – Eric Schneider',
  ogDescription: 'Software portfolio including compilers, operating systems, Minecraft mods, and web projects.',
  ogImage: 'https://eric-unc.tech/eric.png',
  twitterCard: 'summary',
})
</script>